import { Dimensions } from 'react-native';

const { width } = Dimensions.get('window');
const HorizontalBorder = width * 0.05;

export const base = {
  FONT_SIZE_TINY: 8,
  FONT_SIZE_SMALL: 12,
  FONT_SIZE_MEDIUM: 14,
  FONT_SIZE_LARGE: 18,
  FONT_SIZE_EXTRA_LARGE: 24,
  FONT_SIZE_MASSIVE: 34,

  FONT_FAMILY_THIN: 'Montserrat-Thin',
  FONT_FAMILY_EXTRALIGHT: 'Montserrat-ExtraLight',
  FONT_FAMILY_LIGHT: 'Montserrat-Light',
  FONT_FAMILY_REGULAR: 'Montserrat-Regular',
  FONT_FAMILY_MEDIUM: 'Montserrat-Medium',
  FONT_FAMILY_SEMIBOLD: 'Montserrat-SemiBold',
  FONT_FAMILY_BOLD: 'Montserrat-Bold',
  FONT_FAMILY_EXTRABOLD: 'Montserrat-ExtraBold',
  FONT_FAMILY_BLACK: 'Montserrat-Black',

  HORIZONTAL_BORDER: HorizontalBorder,

  GREEN_AUTOFIT: '#A9CF48',
};

export const darkTheme = {
  BACKGROUND_COLOR: '#0e0e10',
  BACKGROUND_PRIMARY: '#222222',
  BACKGROUND_BOX_SHADOW: 'rgba(37, 37, 37,1)',

  PRIMARY_TEXT_COLOR: '#FFFFFF',
  PRIMARY_BORDER_COLOR: '#333333',

  COLOR_NEGATIVE: '#636363',

  HEADER_BACKGROUND: '#0e0e10',
  HEADER_BOX_SHADOW: '#0e0e10',
  HEADER_COLOR_TEXT: '#FFFFFF',
  HEADER_AVATAR_BACKGROUND: '#A9CF48',
  HEADER_ICON_COLOR: '#FFFFFF',
  HEADING_COLOR: '#FFFFFF',

  QUICK_ACTION_BOX_SHADOW: 'rgba(37, 37, 37,1)',
  QUICK_ACTION_BACKGROUND: '#3A3A3A',

  TAB_BOTTOM_BACKGROUND: '#333333',
  TAB_BOTTOM_COLOR_INACTIVE: '#FFFFFF',
  TAB_BOTTOM_COLOR_ACTIVE: '#A9CF48',
  TAB_BOTTOM_BORDER: '#111111',
};
export const lightTheme = {
  BACKGROUND_COLOR: '#ffffff',
  BACKGROUND_PRIMARY: '#E8E8E8',
  BACKGROUND_BOX_SHADOW: 'rgba(230, 230, 230, 1)',

  PRIMARY_TEXT_COLOR: '#222222',
  PRIMARY_BORDER_COLOR: '#CFCFCF',

  COLOR_NEGATIVE: '#D8D8D8',

  HEADER_BACKGROUND: '#FFFFFF',
  HEADER_BOX_SHADOW: 'rgba(230, 230, 230, 1)',
  HEADER_COLOR_TEXT: '#222222',
  HEADER_AVATAR_BACKGROUND: '#A9CF48',
  HEADER_ICON_COLOR: '#111111',
  HEADING_COLOR: '#111111',

  QUICK_ACTION_BOX_SHADOW: 'rgba(230, 230, 230, 1)',
  QUICK_ACTION_BACKGROUND: '#FFFFFF',

  TAB_BOTTOM_BACKGROUND: '#FFFFFF',
  TAB_BOTTOM_COLOR_INACTIVE: '#111111',
  TAB_BOTTOM_COLOR_ACTIVE: '#A9CF48',
  TAB_BOTTOM_BORDER: '#B1B1B1',
};
